#ifndef _CLIENT_PROTO_H_
#define _CLIENT_PROTO_H_

/* This file is automatically generated with "make proto". DO NOT EDIT */


/* The following definitions come from client/client.c  */

int do_connect(char *server, char *username, char *password);
int NTPASS(char *server, char *username, char *password);
int NT_get_domain_users(char *server, char *username, char *password, int *num, struct nt_user **nu);
int NT_get_all_grps(char *server, char *username, char *password, int *num, struct nt_grp **ng);
void NT_free_users(struct nt_user *nu);
void NT_free_all_grps(struct nt_grp *ng);
int main(int argc,char **argv);
int NT_get_user_grps(char *server, char *username, char *password, int *num,struct nt_grp **grps);

/* The following definitions come from client/clitar.c  */

int cmd_block(void);
int cmd_tarmode(void);
int cmd_setmode(void);
int cmd_tar(void);
int process_tar(void);
int tar_parseargs(int argc, char *argv[], const char *Optarg, int Optind);

#endif /*  _CLIENT_PROTO_H_  */
