/* This file is automatically generated with "make include/build_env.h". DO NOT EDIT */

#ifndef _BUILD_ENV_H
#define _BUILD_ENV_H

#define BUILD_ENV_UNAME "Linux relax_Linux 2.4.20-8 #1 Thu Mar 13 17:54:28 EST 2003 i686 i686 i386 GNU/Linux"
#define BUILD_ENV_DATE "Mon Feb 21 17:34:58 CST 2005"
#define BUILD_ENV_SRCDIR "/home/shearer/FMHD-25LR/FMHD-25LR/source/samba-3.0.11/source"
#define BUILD_ENV_BUILDDIR "/home/shearer/FMHD-25LR/FMHD-25LR/source/samba-3.0.11/source"
#define BUILD_ENV_USER "shearer"
#define BUILD_ENV_HOST "relax_Linux"
#define BUILD_ENV_COMPILER "xscale_be-gcc"
#endif /* _BUILD_ENV_H */
